### ISSUE TITLE
Sinon Matchers don't work with the this.mock.expects("method").withArgs

### ISSUE THREAD

**Issue by zcicala** [busterjs/referee-sinon#2]
The Matcher API (http://sinonjs.org/docs/#sinon-match-api) should be able to work with  Buster's mock.  

Examples:
https://gist.github.com/zcicala/6772093

**Comment by dominykas** [comment]
The `noAsserts` gives no asserts, because a `sinon.mock` is used directly, therefore the assertion is never registered - there's no way around it.

The `justFails` works just fine with latest `buster`.
